module.exports = {
  Patent: {
    columns: [
      'registrationNumber',
      'registrationDate',
      'applicationNumber',
      'applicationDate',
      'authors',
      'authorsLatin',
      'patentHolders',
      'patentHoldersLatin',
      'correspondenceAddress',
      'correspondenceAddressLatin',
      'inventionName',
      'patentStartingDate',
      'crimeanInventionApplicationNumberStateRegistrationUkraine',
      'crimeanInventionApplicationDateStateRegistrationUkraine',
      'crimeanInventionPatentNumberUkraine',
      'receiptDateAdditionalDataApplication',
      'dateApplicationWhichAdditionalDataHasBeenReceived',
      'numberApplicationWhichAdditionalDataHasBeenReceived',
      'initialApplicationNumber',
      'initialApplicationDate',
      'initialApplicationPriorityDate',
      'previousApplicationNumber',
      'previousApplicationDate',
      'parisConventionPriorityNumber',
      'parisConventionPriorityDate',
      'parisConventionPriorityCountryCode',
      'PCTApplicationExaminationStartDate',
      'PCTApplicationNumber',
      'PCTApplicationDate',
      'PCTApplicationPublishNumber',
      'PCTApplicationPublishDate',
      'EAApplicationNumber',
      'EAApplicationDate',
      'EAApplicationPublishNumber',
      'EAApplicationPublishDate',
      'applicationPublishDate',
      'applicationPublishNumber',
      'patentGrantPublishDate',
      'patentGrantPublishNumber',
      'revokedPatentNumber',
      'informationAboutObligationConcludeContractAlienation',
      'expirationDate',
      'inventionFormulaNumbersWhichPatentTermProlonged',
      'additionalPatent',
      'actual',
      'publicationURL',
      'createdAt',
      'updatedAt'
    ]  ,
    options: {
        from: 2
      }
  },
};