module.exports = {
  Trademark: {
    columns: [
      'registrationNumber' ,
      'registrationDate' ,
      'applicationNumber' ,
      'applicationDate' ,
      'priorityDate' ,
      'exhibitionPriorityDate' ,
      'parisConventionPriorityNumber' ,
      'parisConventionPriorityDate' ,
      'parisConventionPriorityCountryCode' ,
      'initialApplicationNumber' ,
      'initialApplicationPriorityDate' ,
      'initialRegistrationNumber' ,
      'initialRegistrationDate' ,
      'internationalRegistrationNumber' ,
      'internationalRegistrationDate' ,
      'internationalRegistrationPriorityDate' ,
      'internationalRegistrationEntryDate' ,
      'applicationNumberRecognitionTrademarkFromCrimea' ,
      'applicationDateRecognitionTrademarkFromCrimea' ,
      'crimeanTrademarkApplicationNumberStateRegistrationUkraine' ,
      'crimeanTrademarkApplicationDateStateRegistrationUkraine' ,
      'crimeanTrademarkCertificateNumberUkraine' ,
      'exclusiveRightsTransferAgreementRegistrationNumber' ,
      'exclusiveRightsTransferAgreementRegistrationDate' ,
      'legallyRelatedApplications' ,
      'legallyRelatedRegistrations' ,
      'expirationDate' ,
      'rightHolderName'  ,
      'foreignRightHolderName'  ,
      'rightHolderAddress'  ,
      'rightHolderCountryCode' ,
      'rightHolderOgrn' ,
      'rightHolderInn' ,
      'correspondenceAddress' ,
      'collective' ,
      'collectiveUsers' ,
      'extractionFromCharterCollectiveTrademark' ,
      'colorSpecification' ,
      'unprotectedElements' ,
      'kindSpecification' ,
      'threedimensional' ,
      'threedimensionalSpecification' ,
      'holographic' ,
      'holographicSpecification' ,
      'sound' ,
      'soundSpecification' ,
      'olfactory' ,
      'olfactorySpecification' ,
      'color' ,
      'colorTrademarkSpecification' ,
      'light' ,
      'lightSpecification' ,
      'changing' ,
      'changingSpecification' ,
      'positional' ,
      'positionalSpecification' ,
      'actual' ,
      'publicationURL'
    ]  ,
    options: {
        from: 2
      }
  },
  ProgramRegistry: {
    columns: [
      'registrationNumber',
      'registrationDate',
      'applicationNumber',
      'applicationDate',
      'authors',
      'authorsCount',
      'rightHolders',
      'contactToThirdParties',
      'programName',
      'creationYear',
      'registrationPublishDate',
      'registrationPublishNumber',
      'actual',
      'publicationURL'
    ]  ,
    options: {
        from: 2
      }
  },
  Patent: {
    columns: [
      'registrationNumber',
      'registrationDate',
      'applicationNumber',
      'applicationDate',
      'authors',
      'authorsLatin',
      'patentHolders',
      'patentHoldersLatin',
      'correspondenceAddress',
      'correspondenceAddressLatin',
      'inventionName',
      'patentStartingDate',
      'crimeanInventionApplicationNumberStateRegistrationUkraine',
      'crimeanInventionApplicationDateStateRegistrationUkraine',
      'crimeanInventionPatentNumberUkraine',
      'receiptDateAdditionalDataApplication',
      'dateApplicationWhichAdditionalDataHasBeenReceived',
      'numberApplicationWhichAdditionalDataHasBeenReceived',
      'initialApplicationNumber',
      'initialApplicationDate',
      'initialApplicationPriorityDate',
      'previousApplicationNumber',
      'previousApplicationDate',
      'parisConventionPriorityNumber',
      'parisConventionPriorityDate',
      'parisConventionPriorityCountryCode',
      'pctApplicationExaminationStartDate',
      'pctApplicationNumber',
      'pctApplicationDate',
      'pctApplicationPublishNumber',
      'pctApplicationPublishDate',
      'eaApplicationNumber',
      'eaApplicationDate',
      'eaApplicationPublishNumber',
      'eaApplicationPublishDate',
      'applicationPublishDate',
      'applicationPublishNumber',
      'patentGrantPublishDate',
      'patentGrantPublishNumber',
      'revokedPatentNumber',
      'informationAboutObligationConcludeContractAlienation',
      'expirationDate',
      'inventionFormulaNumbersWhichPatentTermProlonged',
      'additionalPatent',
      'actual',
      'publicationURL'
    ]  ,
    options: {
        from: 2
      }
  },
};
